### ISSUE TITLE
ModuleNotFoundError: No module named 'paramiko.py3compat'

### ISSUE THREAD

**Issue by HB9VQQ** [eoprede/ssh_to_telnet_proxy#5]
Hi,

I am on Ubuntu 22.04.1 LTS. Whe I start /usr/local/bin/ssh_to_telnet_proxy I get

Traceback (most recent call last):
  File "/usr/local/bin/ssh_to_telnet_proxy", line 5, in <module>
    from ssh_to_telnet_proxy.ssh_to_telnet_proxy import main
  File "/usr/local/lib/python3.10/dist-packages/ssh_to_telnet_proxy/ssh_to_telnet_proxy.py", line 17, in <module>
    from paramiko.py3compat import b, u, decodebytes
ModuleNotFoundError: No module named 'paramiko.py3compat'

paramiko is installed:

pip freeze|grep paramiko
paramiko==3.0.0

pip freeze| grep py3compat
py3compat==0.4

Any idea how to fix it?

Thank you

**Comment by eoprede** [comment]
It looks like Paramiko no longer has module py3compat starting form version 3. 
You could downgrade Paramiko to latest version 2 (2.12 I believe), you can also try commenting out the import line (line #17) and see if it all works with 3.

**Comment by HB9VQQ** [comment]
Thank you. Commenting out line #17 worked! Now I am struggling with the correct ssh command.

**Comment by HB9VQQ** [comment]
The ssh proxy is listening on port 7322 on a public-facing server. On the same machine, there is a telnet process running on port 7300. What would be the correct command to access Telnet from the internet through the ssh proxy from a Linux machine?

The Telnet server requires username/password authentication.

Thanks for your help!

**Comment by HB9VQQ** [comment]
Ok I got it 
ssh HB9AZT@localhost@hostname.hb9vqq.ch -p 7322. 

Need to sort carriage returns, output looks a bit strange
